### ISSUE TITLE
Removing all my splits receivers does not return the expected result when querying

### ISSUE THREAD

**Issue by jtourkos** [drips-network/subgraph#2]
Hey @gh0stwheel! 
Here's a small issue I noticed. It's when you're trying to "delete" your split configuration.

Because this is not reproducible unless you use the SDK examples app please feel free to ping me to debug this together!

Steps I followed:

1. Created a new splits configuration.
2. Tried to remove all my split receivers by passing an empty array `[]`.

What happened:

- I still get back my last splits configurations.

Expected behavior:

- Get back an empty array `[]`.

Things to notice:

- I believe the issue is [this line](https://github.com/radicle-dev/drips-subgraph/blob/86cec5cd75c785c1e8edfc298f9c8179a8ba59bf/src/mapping.ts#L195).
- The hashes are _both_ "0x00..." and this results in _not_ entering the if block, hence the split receivers are not updated (to an empty array).
- This is just an assumption, maybe the issue is somewhere else. 😊

Let me know if you need further details.

**Comment by gh0stwheel** [comment]
Hey @jtourkos -- I just pushed a change that I think should fix this. Can you take another look? You shouldn't even need to create more example data or anything -- the splits receivers should now just be removed from your existing test data in the new subgraph deployment.

Let me know! Thanks

**Comment by jtourkos** [comment]
Hi @gh0stwheel -- thanks for taking a look at this. Unfortunately, I still see the same behavior. Try this query, for example:

```
{
  users {
    id
    splitsEntries {
    	id
    }
  }
}
```

It should show 0 entries for all users.

Let's debug this when you're available.

**Comment by gh0stwheel** [comment]
I think we've resolved this now. If not, please re-open!
